---
- name: INSTALL IIS WEB SERVICE
  hosts: '{{ win_target }}'

  tasks:


    - name: STOP IIS SERVICE
      win_service:
        name: W3Svc
        state: stopped

    - name: REMOVE IIS
      win_feature:
        name: Web-Server
        state: absent

    

   