---
- name: Install Application from an MSI 
  hosts: windows

  vars: 
    msi_name: putty-64bit-0.71-installer.msi
    msi_url: "https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.71-installer.msi"
 
  tasks:
    - name: Download the MSI installer
      win_get_url:
        url:  "{{ msi_url }}"
        dest: 'C:\Users\Administrator\Downloads\'

    - name: Install MSI
      win_package: 
        path: 'C:\Users\Administrator\Downloads\{{ msi_name }}'
        state: present
