---
- name: Set Windows Security Policies
  hosts: '{{ tower_hosts_server }}'
  gather_facts: False
  

  roles:
 


  tasks:
    - include_role:
        name: 
        # - change_guest_acct
        # - password_encryption
          - max_password_age
          - system_events
      when: server_os == 'RedHat'

    