---
- name: Set Windows Security Policies
  hosts: '{{ tower_hosts_server }}'
  gather_facts: False
  

  roles:
    - change_guest_acct
    - max_password_age
    - password_encryption
    - system_events

    