---
- name: Set Windows Security Policies
  hosts: '{{ win_target }}'
  gather_facts: False

  roles:
    - change_guest_acct
    - max_password_age
    - password_encryption
    - system_events

    