---
- name: install chocolatey package on Windows host
  hosts: '{{ win_target }}'

  vars:
    choco_packages: git
    app_state: present

  tasks:

    - name: Install multiple packages
      win_chocolatey:
        name: "{{ choco_packages }}"
        state: "{{ app_state }}"


