---
- name: Install initial apps on WIN10 VM
  hosts: '{{ win_target }}'

 
  tasks:

    - name: Install multiple packages
      block:
        - name: INSTALL CHOCO PACKAGES
          win_chocolatey:
              name: " {{ item }}"
              state: present
          with_items: 
              - googlechrome
              - putty
              - winscp
              - 7zip.install
              - microsoft-edge-insider-dev
              - notepadplusplus
              - foxitreader
              - nettime
              - javaruntime
              - sysinternals
              - teamviewer
              - calibre
              - google-drive-file-stream
              
        
        - name: INSTALL FILEBOT 4.7.9
          win_chocolatey:
            name: filebot
            version: 4.7.9
            state: present


