---
- name: Gather Windows Facts
  hosts: '{{ win_target}}'

  tasks:
    - name: Gathering Windows Facts
      debug: 
        msg:  "{{ ansible_os_name }}"

    - set_fact: 
        win_os_family: WIN10WK
        cacheable: true
      when: ansible_os_name | regex_search("Windows 10")

    - set_fact:
         win_os_family: WINSERVER
         cacheable: true
      when: ansible_os_name | regex_search("Windows Server") 


        